---
solution:
  component: ingress

servicePort: 80

hosts:
  - "cluster.example.com"

explicitTLS:

services:
  - name: serviceA
    port: 8081
    userRewrite: true
    contextPath:
      - /
  - name: serviceB
    annotations:
      - nginx.ingress.kubernetes.io/proxy-body-size: 100m
    contextPath:
      - /serviceB
# use rewrites
# userRewrite: true
# services:
#   - name: frontend
#     contextPath:
#       - ()(/.*)
#   - name: api
#     contextPath:
#       - (/api)(/.*)
