---
solution:
  component: ingress

servicePort: 80

hosts:
  - "cluster.example.com"

explicitTLS:
userRewrite: true

services:
  - name: front-end
    contextPath:
      - /()(.*)
  - name: back1
    contextPath:
      - /api/back2(/|$)(.*)
  - name: back2
    contextPath:
      - /api/back2(/|$)(.*)
