{{- define "common.ingress.tpl" -}}
{{- $ingress := default (dict) .Values.ingress -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
{{ template "common.metadata" . }}
  annotations:
    {{ include "common.annotations.ingress.nginx" . | indent 4}}
    {{- if $ingress.annotations }}
    {{ include "common.annote" $ingress.annotations | indent 4 }}
    {{- end }}
spec:
  rules:
  {{- range $host := $ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "common.fullname" $ }}
          servicePort: 80
  {{- end }}
  {{- if $ingress.tls }}
  tls:
{{ toYaml $ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- define "common.ingress" -}}
{{- template "common.util.merge" (append . "common.ingress.tpl") -}}
{{- end -}}
