{{- define "common.serviceaccount.tpl" -}}
{{- $serviceAccount := .Values.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common.serviceAccountName" . }}
  labels:
{{ include "common.labels.standard" . | indent 4 -}}
  {{- with $serviceAccount.annotations }}
  annotations:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
{{- end -}}

{{- define "common.serviceaccount" -}}
{{- $top := first .}}
{{- $serviceAccount := $top.Values.serviceAccount }}
{{- $serviceAccountCreate := default false $serviceAccount.create }}
{{- if and $serviceAccount $serviceAccountCreate }}
{{- template "common.util.merge" (append . "common.serviceaccount.tpl") -}}
{{- end }}
{{- end -}}
