{{- $fullName := include "applicationIngress.fullname" . -}}
{{- $appLabels := include "applicationIngress.labels" . -}}
{{- range .Values.services }}
{{- $contextPath := .contextPath }}
{{- $serviceName := .name }}
{{- $servicePort := .port | default 80 }}
{{- $annotations := .annotations }}
{{- $userRewrite := .userRewrite }}

{{- /* Define default annotations */}}
{{- $defaultAnnotations := dict "kubernetes.io/ingress.class" "nginx" "nginx.ingress.kubernetes.io/service-upstream" "true" "nginx.ingress.kubernetes.io/upstream-vhost" (printf "%s.%s.svc.cluster.local" $serviceName $.Release.Namespace) "nginx.ingress.kubernetes.io/use-regex" "true" }}

{{- /* Add conditional default annotations */}}
{{- if (default $userRewrite false) }}
{{- $_ := set $defaultAnnotations "nginx.ingress.kubernetes.io/rewrite-target" "/$2" }}
{{- end }}

{{- /* Merge annotations from values file, overriding defaults */}}
{{- $mergedAnnotations := mergeOverwrite $defaultAnnotations $annotations }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName}}-{{ $serviceName }}
  labels: {{ $appLabels | nindent 4 }}
  annotations:
    {{- range $key, $value := $mergedAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
    - hosts:
      {{- range $.Values.hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- if $.Values.explicitTLS }}
      secretName: {{ $.Values.explicitTLS }}
      {{- end }}
  rules:
  {{- range $.Values.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
        {{- range $contextPath }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
        {{- end }}
  {{- end }}
{{- end }}
