name: Validate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2

      - name: Validate Ingress
        working-directory: ./charts/application-ingress
        run: |
          helm dependency update
          helm template .

      - name: Validate Demo Service
        working-directory: ./charts/demo-springboot-service
        run: |
          helm dependency update
          helm template .
